export default {
	screens: {
		auth: {
			title: 'Send money easily and quickly',
			start: 'Start',
			logIn: 'Login',
			subTitle: 'Transfer money to your friends without complications',
		},
		dashboard: {
			greeting: 'Hi, {{name}}',
			lastTransactions: 'Last Transactions',
			noTransactions: "You don't have recent transactions",
			send: 'Send',
			deposit: 'Deposit',
			transferTo: 'Withdrawal of',
			depositTo: 'Deposit of',
			portfolio: 'Portfolio',
			balanceTotal: 'Balance total',
			swap: 'Swap',
			swapped: 'Swapped',
			swapBanner: {
				title: 'Swap your USDC for ARST',
				subtitle: 'Exchange quickly and securely',
				button: 'Swap',
			},
			transactionDetails: {
				swap: 'Swap',
				send: 'Withdrawal',
				receive: 'Deposit',
				youSent: 'You sent',
				youReceived: 'You received',
				youSwapped: 'You swapped',
				youReceivedSwap: 'You received',
				amount: 'Amount',
				from: 'From',
				to: 'To',
				alias: 'Alias',
				phone: 'Phone',
				email: 'Email',
				address: 'Address',
				me: 'Me',
			},
		},
		aliasSetup: {
			title: 'Alias Setup',
			subtitle: 'Choose a unique alias that others will see',
			aliasPlaceholder: 'Enter your alias',
			checkAvailability: 'Check availability',
			available: 'This alias is available',
			notAvailable: 'This alias is already taken',
			createAlias: 'Create Alias',
			loading: 'Setting up...',
			aliasDisclamer: 'Entre 4 y 20 caracteres. Solo letras, números y punto.',
			successFeedback: {
				title: 'Welcome',
				description:
					'Thank you for joining Blu Cash. Your cash, but digital. Simple... Fast... Blu.',
			},
			errors: {
				required: 'Please enter your alias',
				tooShort: 'Alias must be at least 3 characters long',
			},
		},
		email: {
			title: 'Continue with Email',
			message: "We'll send a secure code to verify your email",
			placeholder: 'Enter your email',
			sendCode: 'Send code',
			sending: 'Sending...',
			errors: {
				required: 'Please enter your email address',
				invalid: 'Please enter a valid email',
				sendFailed: 'Error sending the code. Please try again.',
			},
		},
		verification: {
			title: 'Enter a 6-digit code',
			message: "We've sent to {{contact}}",
			codePlaceholder: 'Enter 6-digit code',
			notReceived: "Didn't receive the code?",
			resend: 'Resend',
			sending: 'Sending...',
			verifying: 'Verifying...',
			errors: {
				required: 'Please enter the verification code',
			},
		},
		whatsAppLogin: {
			title: 'Continue with WhatsApp',
			message: "We'll send a secure code via WhatsApp to verify your number",
			placeholder: '+1 456-7890',
			sendCode: 'Send code',
			sending: 'Sending...',
			email: 'Email',
			continueWithEmail: 'Or continue with:',
			termsAndConditionsPrefix: 'By creating an account, you agree to our',
			termsAndConditions: 'Terms and Conditions',
			errors: {
				required: 'Please enter your phone number',
				invalid: 'Please enter a valid phone number',
			},
		},
		tabs: {
			home: 'Home',
			send: 'Send',
			profile: 'Profile',
		},
		deposit: {
			title: 'Receive funds',
			subtitle: 'Scan or copy your wallet address to receive funds on {{ network }}',
			disclaimer:
				'Make sure to deposit USDC/ARST from the {{ network }} network. Otherwise, you will lose your funds.',
			network: 'Network',
			acceptedTokens: 'Accepted tokens',
			shareAddress: 'Share',
			shareQrButton: 'Share QR',
			shareAddressButton: 'Share address',
			shareQrDialogTitle: 'Share QR',
			shareQrError: 'Could not share the QR',
			yourWallet: 'Your wallet',
			minAmount: 'Minimum amount',
			comission: 'Commission',
			share: 'This is my address: \n{{ address }}',
			free: 'No commission',
		},
		linkAccount: {
			titleEmail: 'Link your email',
			titlePhone: 'Link your phone number',
			subtitleEmail:
				'By linking an email, you can log in with your email and also receive money using your email, phone number, or alias.',
			subtitlePhone:
				'By linking a phone number, you can log in with your number and also receive money using your email, phone number, or alias.',
			successTitle:
				'Your account was successfully linked. You can now use it to log in or receive money.',
		},
		sessionError: {
			title: 'Oops, something went wrong',
			subtitle: 'Your session encountered an unexpected error. Please log in again to continue.',
			button: 'Log In Again',
		},
		swap: {
			title: 'Swap',
			youSell: 'You sell',
			youReceive: 'You receive',
			balance: 'Balance: ',
			price: 'Price:',
			minimumToReceive: 'Minimum to receive',
			executeSwap: 'Execute Swap',
			processing: 'Processing...',
			success: {
				title: 'Swap successful',
				description: 'Your swap was completed successfully',
			},
			errors: {
				swapError: 'Swap error',
				swapFailed: 'An error occurred while performing the swap',
				prepareSwapFailed: 'An error occurred while preparing the swap',
			},
		},
	},
	send: {
		title: 'Send amount',
		selectToken: 'Select Token',
		chooseToken: 'Choose a token',
		to: 'Alias',
		addressTo: 'Direción de destino',
		networkDisclamer: 'Asegurate de enviar en la red {{ network }}',
		amount: 'Select Amount',
		placeholderTo: 'alias, phone number or email',
		sendTransaction: 'Send',
		loading: 'Sending',
		userExists: 'User found',
		userNoExists: 'User not found',
		bottomSheet: {
			title: 'How would you like to make the payment',
			methodQR: 'Scan Blu QR',
			methodUser: 'To a Blu user',
			methodCripto: 'To a crypto wallet',
		},
		feedback: {
			success: 'Successful transfer!',
			errorTitle: 'Transfer error',
			errorSubtitle: 'An error occurred during the transfer. Please try again later',
		},
		errors: {
			insufficientBalance: 'Insufficient balance',
			invalidAddress: 'Invalid address',
			required: 'This field is required',
			minimumAmount: 'The minimum amount is 0.01',
		},
	},
	profile: {
		title: 'Profile',
		memberSince: 'Member since',
		networkAndAlias: 'Networks & Alias',
		chainId: 'Chain ID',
		userAlias: 'User Alias',
		primary: 'PRIMARY',
		noAlias: 'No alias set',
		aliasSubtext: 'Easy way to receive payments instead of using your wallet address',
		aliasPlaceholder: 'your.alias',
		aliasUpdated: 'Alias updated successfully',
		walletAddress: 'Wallet Address',
		accountSettings: 'Account Settings',
		editProfile: 'Edit Profile',
		security: 'Security',
		helpAndSupport: 'Help & Support',
		termsAndConditions: 'Terms and Conditions',
		privacyPolicy: 'Privacy Policy',
		deleteAccount: 'Delete my account',
		deleteAccountDisclaimer: 'This feature will be available soon.',
		logout: 'Log Out',
		copied: 'Copied!',
		addressCopied: 'Address copied to clipboard',
		aliasCopied: 'Alias copied to clipboard',
		shareAddress: 'My wallet address: {{address}}',
		shareAlias: 'Send me crypto using my alias: {{alias}}',
		phone: 'Phone',
		email: 'Email',
		linkEmail: 'Link Email',
		linkPhone: 'Link Phone Number',
	},
	qr: {
		title: 'Scan the QR code',
		openSettings: 'Open settings',
		requestPermission: 'Grant permission',
		cameraPermission: 'Enable camera permissions to continue',
		cameraNeedPermission: 'We need access to your camera',
		cameraPermissionSubtitle: 'To continue, please grant camera permission.',
		cameraPermissionMessage:
			'We will redirect you to your phone settings, from there enable camera permissions.',
	},
	common: {
		loading: 'Loading...',
		error: 'Error',
		success: 'Success',
		cancel: 'Cancel',
		confirm: 'Confirm',
		next: 'Next',
		back: 'Back',
		gotIt: 'Got it',
		copied: 'Copied',
	},
	errors: {
		GAS_SPONSORSHIP_POLICY_BLOCK: 'Gas sponsorship policy block',
		TRANSACTION_FAILED: 'Transaction failed',
		INTERNAL_SERVER_ERROR: 'Oops, something went wrong',
		CODE_INVALID_OR_PHONE: 'Invalid code and phone combination',
		CODE_INVALID_OR_EMAIL: 'Invalid code and email combination',
		PHONE_ALREADY_LINKED: 'This phone number is already linked to another account',
		EMAIL_ALREADY_LINKED: 'This email is already linked to another account',
		USER_NOT_ALLOWED: 'User not enabled. To register, please contact the Blu Cash team',
	},
};
