export default {
	screens: {
		auth: {
			title: 'Enviá dinero de forma rápida y segura',
			start: 'Comenzar',
			logIn: 'Iniciar sesión',
			subTitle: 'Transferí dinero a tus contactos sin complicaciones',
		},
		dashboard: {
			greeting: 'Hola, {{name}}',
			lastTransactions: 'Actividad reciente',
			noTransactions: 'No tenés ningún movimiento',
			send: 'Enviar',
			deposit: 'Ingresar',
			transferTo: 'Retiro',
			depositTo: 'Ingreso',
			portfolio: 'Saldo disponible',
			balanceTotal: 'Saldo total',
			swap: 'Swap',
			swapped: 'Intercambiaste',
			swapBanner: {
				title: 'Convertí tus USDC en ARST',
				subtitle: 'Fácil, rápido y seguro.',
				button: 'Intercambiar',
			},
			transactionDetails: {
				swap: 'USDC ⇆ ARST',
				send: 'Retiro',
				receive: 'Ingreso',
				youSent: 'Enviaste',
				youReceived: 'Recibiste',
				youSwapped: 'Cambiaste',
				youReceivedSwap: 'Recibiste',
				amount: 'Monto',
				from: 'Quién envió',
				to: 'Quién recibe',
				alias: 'Alias',
				phone: 'Teléfono',
				email: 'Correo',
				address: 'Address',
				me: 'Yo',
			},
		},
		aliasSetup: {
			title: 'Creá tu alias',
			subtitle: 'Tu alias es único y sirve para que te envíen dinero de forma rápida y segura',
			aliasPlaceholder: 'juan.perez',
			checkAvailability: 'Verificar disponibilidad',
			available: 'Este alias está disponible',
			notAvailable: 'El alias ya está en uso',
			createAlias: 'Crear Alias',
			loading: 'Configurando...',
			aliasDisclamer: 'Entre 4 y 20 caracteres. Solo letras, números y punto.',
			successFeedback: {
				title: 'Bienvenido',
				description:
					'Gracias por sumarte a Blu Cash. Tu dinero en efectivo, pero digital. Simple... Rápido... Blu.',
			},
			errors: {
				required: 'Por favor ingresa tu alias',
				tooShort: 'El alias debe tener al menos 3 caracteres',
			},
		},
		email: {
			title: 'Continuar con correo electrónico',
			message: 'Te enviaremos un código seguro para verificar tu email',
			placeholder: 'Ingresa tu email',
			sendCode: 'Enviar código',
			sending: 'Enviando...',
			errors: {
				required: 'Por favor ingresa tu dirección de email',
				invalid: 'Por favor ingresa un email válido',
				sendFailed: 'Error al enviar el código. Por favor intenta de nuevo.',
			},
		},
		verification: {
			title: 'Ingresa el código de 6 dígitos',
			message: 'Te lo mandamos a {{contact}}',
			codePlaceholder: 'Ingresa el código de 6 dígitos',
			notReceived: '¿No te llegó el código?',
			resend: 'Reenviar',
			sending: 'Enviando...',
			verifying: 'Verificando...',
			errors: {
				required: 'Por favor ingresa el código de verificación',
			},
		},
		whatsAppLogin: {
			title: 'Ingresar con WhatsApp',
			message: 'Te vamos a enviar un código para confirmar tu número/email',
			placeholder: '(351) 3175389',
			sendCode: 'Enviar código',
			sending: 'Enviando...',
			email: 'Correo electrónico',
			continueWithEmail: 'O continúa con:',
			termsAndConditionsPrefix: 'Al crear una cuenta, aceptas nuestros',
			termsAndConditions: 'Términos y Condiciones',
			errors: {
				required: 'Por favor ingresa tu número de teléfono',
				invalid: 'Por favor ingresa un número válido',
			},
		},
		tabs: {
			home: 'Inicio',
			send: 'Enviar',
			profile: 'Perfil',
		},
		deposit: {
			title: 'Ingresar dinero',
			subtitle: 'Escaneá o copiá tu dirección para recibir dinero en {{ network }}',
			disclaimer:
				'Asegurate de depositar USDC/ARST desde la red {{ network }}. De lo contrario, perderás tus fondos.',
			network: 'Red',
			acceptedTokens: 'Tokens aceptados',
			shareAddress: 'Compartir',
			shareQrButton: 'Compartir QR',
			shareAddressButton: 'Compartir dirección',
			shareQrDialogTitle: 'Compartir QR',
			shareQrError: 'No se pudo compartir el QR',
			yourWallet: 'Tu billetera',
			minAmount: 'Monto mínimo',
			comission: 'Comisión',
			share: 'Esta es mi dirección: \n{{ address }}',
			free: 'Sin comisión',
		},
		linkAccount: {
			titleEmail: 'Vincula tu correo electrónico',
			titlePhone: 'Vincula tu número de teléfono',
			subtitleEmail:
				'Al vincular un correo electrónico podrás iniciar sesión con tu correo y también recibir dinero usando tu correo, tu número de teléfono o tu alias.',
			subtitlePhone:
				'Al vincular un número de teléfono podrás iniciar sesión con tu número y también recibir dinero usando tu correo, tu número de teléfono o tu alias.',
			successTitle:
				'Tu cuenta se vinculó correctamente. Ahora puedes usarla para iniciar sesión o recibir dinero.',
		},
		sessionError: {
			title: 'Ups, algo salió mal',
			subtitle: 'Tu sesión tuvo un error inesperado. Vuelve a iniciar sesión para continuar.',
			button: 'Volver a iniciar sesión',
		},
		swap: {
			title: 'USDC ⇆ ARST',
			youSell: 'Vendés',
			youReceive: 'Recibís',
			balance: 'Balance: ',
			price: 'Precio:',
			minimumToReceive: 'Mínimo a recibir',
			executeSwap: 'Convertir ahora',
			processing: 'Procesando...',
			success: {
				title: 'Compraste tus ARST',
				description: 'Ya están en tu billetera para usarlos cuando quieras.',
			},
			errors: {
				swapError: 'Error en el intercambio',
				swapFailed: 'Ocurrió un error al realizar el intercambio',
				prepareSwapFailed: 'Ocurrió un error al preparar el intercambio',
			},
		},
	},
	send: {
		title: 'Enviar saldo',
		selectToken: 'Seleccionar moneda',
		chooseToken: 'Elige una moneda',
		to: 'Alias',
		addressTo: 'Direción de destino',
		networkDisclamer: 'Asegurate de enviar en la red {{ network }}',
		amount: 'Selecionar monto',
		placeholderTo: 'Alias, correo o número de teléfono',
		sendTransaction: 'Confirmar',
		loading: 'Enviando',
		userExists: 'Usuario encontrado',
		userNoExists: 'No encontramos al usuario',
		bottomSheet: {
			title: '¿Cómo te gustaría realizar el envío?',
			methodQR: 'Escanear QR de Blu',
			methodUser: 'Enviar a un usuario de Blu',
			methodCripto: 'Enviar a una billetera cripto',
		},
		feedback: {
			success: '¡Envío exitoso!',
			errorTitle: 'Error en el envío',
			errorSubtitle: 'Ocurrió un error en el durante el envío Por favor, intentalo más tarde',
		},
		errors: {
			insufficientBalance: 'Saldo insuficiente',
			invalidAddress: 'Dirección inválida',
			required: 'Este campo es obligatorio',
			minimumAmount: 'El monto mínimo es 0.01',
		},
	},
	profile: {
		title: 'Perfil',
		memberSince: 'Miembro desde el',
		networkAndAlias: 'Datos de la cuenta',
		chainId: 'ID',
		userAlias: 'Alias',
		primary: 'PRINCIPAL',
		noAlias: 'Sin alias configurado',
		aliasSubtext: 'Forma fácil de recibir pagos',
		aliasPlaceholder: 'tu.alias',
		aliasUpdated: 'Alias actualizado correctamente',
		walletAddress: 'Dirección de Billetera',
		accountSettings: 'Configuración de Cuenta',
		editProfile: 'Editar Perfil',
		security: 'Seguridad',
		helpAndSupport: 'Ayuda y Soporte',
		termsAndConditions: 'Términos y Condiciones',
		privacyPolicy: 'Política de Privacidad',
		deleteAccount: 'Dar de baja mi cuenta',
		deleteAccountDisclaimer: 'Esta función estará disponible próximamente.',
		logout: 'Cerrar Sesión',
		copied: '¡Copiado!',
		addressCopied: 'Dirección copiada al portapapeles',
		aliasCopied: 'Alias copiado al portapapeles',
		shareAddress: 'Mi dirección de billetera: {{address}}',
		shareAlias: 'Envíame saldo usando mi alias: {{alias}}',
		email: 'Email',
		linkEmail: 'Vincular Email',
		phone: 'Teléfono',
		linkPhone: 'Vincular Número de Teléfono',
	},
	qr: {
		title: 'Escanea el código QR',
		openSettings: 'Abrir configuración',
		requestPermission: 'Dar permiso',
		cameraPermission: 'Habilita los permisos de tu cámara para continuar',
		cameraNeedPermission: 'Necesitamos acceso a tu cámara',
		cameraPermissionSubtitle: 'Para continuar, por favor otorga permiso de la cámara.',
		cameraPermissionMessage:
			'Te vamos a redirigir a la configuración de tu teléfono, desde ahí habilita los permisos de la cámara.',
	},

	common: {
		loading: 'Cargando...',
		error: 'Error',
		success: 'Éxito',
		cancel: 'Cancelar',
		confirm: 'Confirmar',
		next: 'Siguiente',
		back: 'Atrás',
		gotIt: 'Listo',
		copied: 'Copiado',
	},
	errors: {
		GAS_SPONSORSHIP_POLICY_BLOCK: 'Bloqueo de política de patrocinio de gas',
		TRANSACTION_FAILED: 'Transacción fallida',
		INTERNAL_SERVER_ERROR: 'Ups, algo salió mal',
		CODE_INVALID_OR_PHONE: 'Combinación de teléfono y código inválida',
		CODE_INVALID_OR_EMAIL: 'Combinación de email y código inválida',
		PHONE_ALREADY_LINKED: 'Este número de teléfono ya está vinculado a otra cuenta',
		EMAIL_ALREADY_LINKED: 'Este email ya está vinculado a otra cuenta',
		USER_NOT_ALLOWED:
			'Usuario no habilitado. Para poder registrarte contactá al equipo de Blu Cash',
	},
};
